### ISSUE TITLE
MLF Date-A-Scientist Grade Summary

### ISSUE THREAD

**Issue by mackenzieyoung** [r-cao/date-a-scientist#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, your code runs without any errors.
 
### Criteria 2: Exploration of Data
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very good job extensively exploring the data and drawing conclusions about how to proceed based on what you found. I especially like how you determined the average male and female users. One note is that your exploratory analysis should have informed you that some aspects of your research question, like whether you can predict age from income, were never going to be successful (see your scatter plot of age vs. income, there definitely does not appear to be a linear relationship there!)
 
### Criteria 3: Machine Learning Techniques used correctly
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very nice job using and explaining the machine learning algorithms. You did a particularly good job outlining why each one was suited for the particular research question you used it for.
 
### Criteria 4: Report: Are conclusions clear and supported by data?
* _Score Level:_ 3 (Meets expectations)
* _Comment(s):_ Nice job in your presentation, but one thing that's missing is a little more analysis of the results. For example, putting some of the plots in your presentation would have strengthened your conclusions. Also, even though your SVM model gets ~60% accuracy, since chance is 50% (male or female), it still isn't doing a great job!

### Criteria 5: Code formatting
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very good job, your code was clear and easy to read. Nice job using Jupyter notebooks to format it, it allowed you to really walk your reader through your analysis. 
 
### Overall Score: 19/20
Great job overall!

**Comment by r-cao** [comment]
Thank you for the feedback. Very helpful in understanding the areas the I need to improve in.

I have a question: if i was to analyzing income vs age - what would be the a recommended approach?

**Comment by mackenzieyoung** [comment]
I don't think you did it incorrectly, there just wasn't a relationship there to begin with!

**Comment by r-cao** [comment]
Thanks
